[package]
name = "creative-coding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.4.6",features = ["derive"]}
nannou = "0.18.1"
nannou_egui = "0.5.0"
